config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  authenticated :user do
    root 'tasks#index', as: 'authenticated_root'
  end

  resources :tasks, except: :index do
    scope module: 'tasks' do
      resource :complete, only: %i[create destroy], controller: 'completed_tasks'
    end
  end

  scope module: 'tasks' do
    resource :completed_tasks, only: :destroy, controller: 'all_completed_tasks'
  end

  resources :categories, except: :show do
    scope module: 'categories' do
      resources :tasks, only: %i[new index]
      resource :completed_tasks, only: :destroy, controller: 'all_completed_tasks'
    end
  end

  root 'static_pages#home'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :name, presence: true

  scope :not_completed_deadline_today, -> { not_completed.deadline_today.asc_name }
  scope :not_completed_deadline_not_today, -> { deadline_not_today.or(deadline_nil).not_completed.asc_deadline }
  scope :completed_asc_name, -> { completed.asc_name }

  scope :asc_deadline, -> { order(:deadline) }
  scope :asc_name, -> { order(:name) }
  scope :deadline_nil, -> { where(deadline: nil) }
  scope :deadline_not_today, -> { where.not(deadline: Date.current) }
  scope :deadline_today, -> { where(deadline: Date.current) }
  scope :completed, -> { where(completed: true) }
  scope :not_completed, -> { where(completed: false) }

  def complete
    update_attribute(:completed, true)
  end

  def uncomplete
    update_attribute(:completed, false)
  end
end

app/controllers/categories/tasks_controller.rb
class Categories::TasksController < ApplicationController
  include CategoryScoped

  before_action :store_location, only: :index

  def index
    @tasks_today = @category.tasks.not_completed_deadline_today
    @tasks_not_completed = @category.tasks.not_completed_deadline_not_today
    @tasks_completed = @category.tasks.completed_asc_name
  end

  def new
    @categories = set_category_collection
    @task = @category.tasks.build
    render 'tasks/new'
  end

  private

  def set_category_collection
    current_user.categories.asc_name
  end
end

app/controllers/tasks/all_completed_tasks_controller.rb
class Tasks::AllCompletedTasksController < ApplicationController
  def destroy
    current_user.tasks.completed.destroy_all
    redirect_to root_url, success: 'Successfully deleted all completed tasks in this category.'
  end
end

app/controllers/tasks/completed_tasks_controller.rb
class Tasks::CompletedTasksController < ApplicationController
  include TaskScoped

  def create
    @task.complete
    redirect_back(fallback_location: root_url)
  end

  def destroy
    @task.uncomplete
    redirect_back(fallback_location: root_url)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :set_category_collection, only: %i[new create edit update]
  before_action :store_location, only: :index

  def index
    tasks = current_user.tasks.includes(:category)
    @tasks_today = tasks.not_completed_deadline_today
    @tasks_not_completed = tasks.not_completed_deadline_not_today
    @tasks_completed = tasks.completed_asc_name
  end

  def new
    @task = current_user.tasks.build
  end

  def show; end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to previous_location(fallback: @task), success: "Successfully added #{@task.name.inspect} task."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to @task, success: "Successfully updated #{@task.name.inspect} task."
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to previous_location(fallback: root_url), success: "Successfully deleted #{@task.name.inspect} task."
  end

  private

  def task_params
    params.require(:task).permit(:name, :deadline, :details, :category_id)
  end

  def set_category_collection
    @categories = current_user.categories.asc_name
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/helpers/categories/tasks_helper.rb
module Categories::TasksHelper
end

app/helpers/tasks/all_completed_tasks_helper.rb
module Tasks::AllCompletedTasksHelper
end

app/helpers/tasks/completed_tasks_helper.rb
module Tasks::CompletedTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def show_task_details(task_detail)
    task_detail.blank? ? 'No details provided.' : task_detail
  end

  def show_task_state(task)
    task.completed? ? 'Completed' : 'Not Completed'
  end
end

app/views/tasks/_form.html.erb
<%= render 'shared/error_msg', object: @task %>
<%= form_with model: @task, html: {class: 'bg-slate-100 max-w-lg m-auto p-6 rounded-md mt-4'} do |f|%>
  <h1 class= 'font-bold text-4xl text-center mb-4'><%= yield(:title) %></h1>
  <div class="flex flex-col">
    <%= f.label :category_id, class: 'text-2xl'%>
    <%= f.collection_select :category_id, @categories, :id, :name, {include_blank: 'Select Category'}, {class: 'rounded-md w-full text-xl'}%>
  </div>
  <div class="flex flex-col mt-2">
    <%= f.label :name, class: 'text-2xl' %>
    <%= f.text_field :name, class: 'rounded-md w-full text-xl' %>
  </div>
  <div class="flex flex-col mt-2">
    <%= f.label :details, class: 'text-2xl' %>
    <%= f.text_area :details, class: 'rounded-md w-full text-xl resize-none' %>
  </div>
  <div class="flex flex-col mt-2">
    <%= f.label :deadline, class: 'text-2xl' %>
    <%= f.date_field :deadline, class: 'rounded-md w-full text-xl' %>
  </div>
  <%= f.submit yield(:form_button_text), class: 'mt-4 bg-slate-400 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-300 w-full' %>
<% end %>

app/views/tasks/edit.html.erb
<% provide(:title, "Edit Task")%>
<% provide(:form_button_text, "Update Task")%>
<%= render 'form' %>

app/views/tasks/index.html.erb
<% provide(:title, "Tasks")%>
<div class="text-center mb-5">
  <h1 class= "font-bold text-4xl mb-4"> Welcome, <%= get_email_username(current_user.email) %>! </h1>
  <div>
    <%= link_to new_category_path, class: 'bg-slate-400 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-500 mr-2' do %>
      <i class="las la-plus"></i>Add Category 
    <% end %>
    <% if current_user.categories.count > 0 %>
      <%= link_to new_task_path, class: 'bg-slate-400 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-500' do %>
        <i class="las la-plus"></i>Add Task
      <% end %>
    <% end %>
  </div>
</div>
<%= render 'shared/task_list'%>

app/views/tasks/new.html.erb
<% provide(:title, "Add Task")%>
<% provide(:form_button_text, "Add Task")%>
<%= render 'tasks/form' %>

app/views/tasks/show.html.erb
<% provide(:title, @task.name)%>
<div class="bg-slate-100 flex flex-col items-center justify-center gap-6 max-w-2xl py-6 px-8 rounded-md m-auto">
  <h1 class="font-bold text-4xl"><%= @task.name %></h1>
  <div>
    <%= link_to edit_task_path, class: 'bg-slate-400 p-2 mr-2 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-300' do %>
      <i class="las la-edit"></i>Edit
    <% end %>
    <%= link_to @task, method: :delete, data: { confirm: "Are you sure you want to delete this task?" }, class: 'bg-slate-400 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-300' do %>
      <i class="las la-trash-alt"></i>Delete
    <% end %>
  </div>
  <p class='w-full text-center <%= @task.completed ? 'bg-green-400' : 'bg-yellow-400' %> rounded-md p-4 text-2xl font-bold'><%= show_task_state(@task) %></p>
  <div class='w-full'>
    <h2 class='font-bold text-3xl text-center'>Details</h2>
    <p class="bg-slate-300 p-4 rounded-md text-xl font-medium whitespace-pre-wrap <%= 'text-center' if @task.details.blank? %>"><%= show_task_details(@task.details) %></p>
  </div>
  <div class='w-full'>
    <h2 class='font-bold text-3xl text-center'>Deadline</h2>
    <p class="p-4 rounded-md text-2xl font-medium text-center <%= turn_to_red(@task.deadline, @task.completed) %>"><%= rephrase_deadline(@task.deadline)%></p>
  </div>
</div>