config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  authenticated :user do
    root 'tasks#index', as: 'authenticated_root'
  end

  resources :tasks, except: :index do
    scope module: 'tasks' do
      resource :complete, only: %i[create destroy], controller: 'completed_tasks'
    end
  end

  scope module: 'tasks' do
    resource :completed_tasks, only: :destroy, controller: 'all_completed_tasks'
  end

  resources :categories, except: :show do
    scope module: 'categories' do
      resources :tasks, only: %i[new index]
      resource :completed_tasks, only: :destroy, controller: 'all_completed_tasks'
    end
  end

  root 'static_pages#home'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, uniqueness: { scope: :user_id }, presence: true, length: { maximum: 24 }
  scope :asc_name, -> { order(:name) }
end

app/controllers/categories/all_completed_tasks_controller.rb
class Categories::AllCompletedTasksController < ApplicationController
  include CategoryScoped

  def destroy
    @category.tasks.completed.destroy_all
    redirect_to category_tasks_url(@category), success: 'Successfully deleted all completed tasks in this category.'
  end
end

app/controllers/categories/completed_tasks_controller.rb
class Categories::CompletedTasksController < ApplicationController
  include CategoryScoped

  def destroy_all
    @category.tasks.completed.destroy_all
    redirect_to category_tasks_url(@category), success: 'Successfully deleted all completed tasks in this category.'
  end
end

app/controllers/categories/tasks_controller.rb
class Categories::TasksController < ApplicationController
  include CategoryScoped

  before_action :store_location, only: :index

  def index
    @tasks_today = @category.tasks.not_completed_deadline_today
    @tasks_not_completed = @category.tasks.not_completed_deadline_not_today
    @tasks_completed = @category.tasks.completed_asc_name
  end

  def new
    @categories = set_category_collection
    @task = @category.tasks.build
    render 'tasks/new'
  end

  private

  def set_category_collection
    current_user.categories.asc_name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = current_user.categories.asc_name
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to category_tasks_url(@category), success: "Successfully added #{@category.name.inspect} category."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to category_tasks_url(@category), success: "Successfully updated #{@category.name.inspect} category."
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, success: "Successfully deleted #{@category.name.inspect} category."
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = current_user.categories.find(params[:id])
  end
end

app/helpers/categories/all_completed_tasks_helper.rb
module Categories::AllCompletedTasksHelper
end

app/helpers/categories/tasks_helper.rb
module Categories::TasksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def count_not_completed_task(category)
    category.tasks.not_completed.count
  end

  def count_completed_task(category)
    category.tasks.completed.count
  end
end

app/views/categories/_category.html.erb
<li class="bg-slate-300 p-4 rounded-md w-64 h-64 m-auto hover:bg-slate-400">
  <div class="flex flex-col h-full justify-between">
    <%= link_to category_tasks_path(category), class: 'flex flex-col justify-between gap-5' do %>
      <h1 class="font-bold text-3xl h-16 break-words"><%= category.name %></h1>
      <div class="text-left mb-5 text-center mt-5">
        <p class="text-lg font-medium"><i class="las la-list mr-1"></i><%= count_not_completed_task(category)%> incomplete <%= "task".pluralize(count_not_completed_task(category)) %></p>
        <p class="text-lg font-medium"><i class="las la-check-square mr-1"></i><%= count_completed_task(category)%> completed <%= "task".pluralize(count_completed_task(category)) %></p>
      </div>
    <% end %>
    <%= link_to category, method: :delete, data: { confirm: 'Are you sure you want to delete this category?'} do %>
      <div class='bg-slate-500 text-center rounded-lg hover:bg-slate-600'>
        <i class="las la-trash-alt la-lg"></i>
      </div>
    <% end %>
  </div>
</li>

app/views/categories/_form.html.erb
<%= render 'shared/error_msg', object: @category %>
<%= form_with model: @category, html: {class: 'bg-slate-100 max-w-md m-auto p-6 rounded-md mt-4'} do |f| %>
  <div class= 'flex flex-col gap-1'>
    <h1 class='text-4xl text-center font-bold'><%= yield(:title) %></h1>
    <%= f.label :name, class: 'text-2xl mt-2' %>
    <%= f.text_field :name, class: 'rounded-md w-full' %>
  </div>
  <%= f.submit yield(:form_button_text), class: 'mt-4 bg-slate-400 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-300 w-full' %>
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, "Edit Category") %>
<% provide(:form_button_text, "Rename Category")%>
<%= render 'form' %>

app/views/categories/index.html.erb
<% provide(:title, "Categories")%>
<div class="text-center">
  <h1 class="font-bold text-4xl mb-4">Categories</h1>
  <%= link_to new_category_path, class: 'bg-slate-400 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-500 mr-2' do %>
    <i class="las la-plus"></i>Add Category 
  <% end %>
</div>
<div class='bg-slate-100 rounded-md m-6 p-4'>
  <% if @categories.count > 0 %>
    <ul class='grid grid-cols-auto-fill-64 justify-center gap-4 text-center '>
      <%= render @categories %>
    </ul>
  <% else %>
    <p class="font-semibold text-center text-2xl">There are no categories to be shown.</p>
  <% end %>
</div>

app/views/categories/new.html.erb
<% provide(:title, "Add Category") %>
<% provide(:form_button_text, "Add Category")%>
<%= render 'form' %>

app/views/categories/show.html.erb
<% provide(:title, @category.name)%>
<div class="text-center">
  <h1 class="font-bold text-4xl mb-4"><%= @category.name %></h1>
  <%= link_to edit_category_path, class: 'bg-slate-400 p-2 mr-1 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-300' do %>
    <i class="las la-edit"></i>Rename
  <% end %>
  <%= link_to @category, method: :delete, data: { confirm: "Are you sure you want to delete this category?" }, class: 'bg-slate-400 p-2 mr-1 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-500' do %>
    <i class="las la-trash-alt"></i>Delete
  <% end %>
  <%= link_to new_category_task_path(@category), class: 'bg-slate-400 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-slate-500' do %>
    <i class="las la-plus"></i>Add Task
  <% end %>
</div>
<%= render 'shared/task_list' %>