config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  authenticated :user do
    root 'tasks#index', as: 'authenticated_root'
  end

  resources :tasks, except: :index do
    scope module: 'tasks' do
      resource :complete, only: %i[create destroy], controller: 'completed_tasks'
    end
  end

  scope module: 'tasks' do
    resource :completed_tasks, only: :destroy, controller: 'all_completed_tasks'
  end

  resources :categories, except: :show do
    scope module: 'categories' do
      resources :tasks, only: %i[new index]
      resource :completed_tasks, only: :destroy, controller: 'all_completed_tasks'
    end
  end

  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, uniqueness: { scope: :user_id }, presence: true, length: { maximum: 24 }
  scope :asc_name, -> { order(:name) }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :name, presence: true

  scope :not_completed_deadline_today, -> { not_completed.deadline_today.asc_name }
  scope :not_completed_deadline_not_today, -> { deadline_not_today.or(deadline_nil).not_completed.asc_deadline }
  scope :completed_asc_name, -> { completed.asc_name }

  scope :asc_deadline, -> { order(:deadline) }
  scope :asc_name, -> { order(:name) }
  scope :deadline_nil, -> { where(deadline: nil) }
  scope :deadline_not_today, -> { where.not(deadline: Date.current) }
  scope :deadline_today, -> { where(deadline: Date.current) }
  scope :completed, -> { where(completed: true) }
  scope :not_completed, -> { where(completed: false) }

  def complete
    update_attribute(:completed, true)
  end

  def uncomplete
    update_attribute(:completed, false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :confirmable

  has_many :categories, dependent: :destroy
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  add_flash_types :success, :danger

  private

  def store_location
    session[:previous_page] = request.original_url
  end

  def previous_location(fallback:)
    session.delete(:previous_page) || fallback
  end
end

app/controllers/categories/tasks_controller.rb
class Categories::TasksController < ApplicationController
  include CategoryScoped

  before_action :store_location, only: :index

  def index
    @tasks_today = @category.tasks.not_completed_deadline_today
    @tasks_not_completed = @category.tasks.not_completed_deadline_not_today
    @tasks_completed = @category.tasks.completed_asc_name
  end

  def new
    @categories = set_category_collection
    @task = @category.tasks.build
    render 'tasks/new'
  end

  private

  def set_category_collection
    current_user.categories.asc_name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = current_user.categories.asc_name
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to category_tasks_url(@category), success: "Successfully added #{@category.name.inspect} category."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to category_tasks_url(@category), success: "Successfully updated #{@category.name.inspect} category."
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, success: "Successfully deleted #{@category.name.inspect} category."
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = current_user.categories.find(params[:id])
  end
end

app/controllers/concerns/category_scoped.rb
module CategoryScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_category
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end
end

app/controllers/concerns/task_scoped.rb
module TaskScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_task
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:task_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home; end
end

app/controllers/tasks/completed_tasks_controller.rb
class Tasks::CompletedTasksController < ApplicationController
  include TaskScoped

  def create
    @task.complete
    redirect_back(fallback_location: root_url)
  end

  def destroy
    @task.uncomplete
    redirect_back(fallback_location: root_url)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :set_category_collection, only: %i[new create edit update]
  before_action :store_location, only: :index

  def index
    tasks = current_user.tasks.includes(:category)
    @tasks_today = tasks.not_completed_deadline_today
    @tasks_not_completed = tasks.not_completed_deadline_not_today
    @tasks_completed = tasks.completed_asc_name
  end

  def new
    @task = current_user.tasks.build
  end

  def show; end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to previous_location(fallback: @task), success: "Successfully added #{@task.name.inspect} task."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to @task, success: "Successfully updated #{@task.name.inspect} task."
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to previous_location(fallback: root_url), success: "Successfully deleted #{@task.name.inspect} task."
  end

  private

  def task_params
    params.require(:task).permit(:name, :deadline, :details, :category_id)
  end

  def set_category_collection
    @categories = current_user.categories.asc_name
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  after_action :remove_notice, only: %i[destroy create]

  private

  def remove_notice
    flash.delete(:notice)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = '')
    base_title = 'Punctual'
    title.empty? ? base_title : "#{title} | #{base_title}"
  end

  def get_email_username(email)
    email.split('@')[0]
  end

  def format_auxiliary_verb(count)
    count == 1 ? 'is' : 'are'
  end

  def rephrase_deadline(date)
    if date == Date.current
      'Today'
    elsif date == Date.tomorrow
      'Tomorrow'
    elsif date.is_a?(Date)
      date
    else
      '---'
    end
  end

  def turn_to_red(date, completed)
    return 'bg-slate-300' if date.blank?

    date < Date.current && !completed ? 'bg-red-400' : 'bg-slate-300'
  end

  def conditional_destroy_completed_path(category)
    category ? category_completed_tasks_path(category) : completed_tasks_path
  end
end

app/helpers/categories/tasks_helper.rb
module Categories::TasksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def count_not_completed_task(category)
    category.tasks.not_completed.count
  end

  def count_completed_task(category)
    category.tasks.completed.count
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks/all_completed_tasks_helper.rb
module Tasks::AllCompletedTasksHelper
end

app/helpers/tasks/completed_tasks_helper.rb
module Tasks::CompletedTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def show_task_details(task_detail)
    task_detail.blank? ? 'No details provided.' : task_detail
  end

  def show_task_state(task)
    task.completed? ? 'Completed' : 'Not Completed'
  end
end

app/views/layouts/_aside.html.erb
<aside>
  <ul>
    <li><%= link_to "Categories", categories_path %></li>
  </ul>
</aside>

app/views/layouts/_header.html.erb
 <nav class="flex justify-between items-center h-16 px-5 md:px-16 w-full bg-slate-700 relative">
  <%= link_to root_path, class: "text-white text-xl sm:text-2xl font-bold sm:w-auto w-fit" do %>
    <div class="flex gap-3 items-center ">
      <div class="flex gap-2 items-center"><i class="las la-user-clock"></i>
        <p class="hidden lg:inline-block">Punctual</p>
        <% if user_signed_in? %>
          <p class="text-sm md:text-md lg:text-xl sm:font-medium">| <%= current_user.email %></p>
        <%end%>
      </div>
    </div>
  <% end %>
  <span id="hamburger" class="sm:hidden text-white text-lg font-bold">&#9776;</span>
  <ul id="list" class="hidden gap-0 bg-slate-700 flex flex-col absolute top-0 right-0 mt-16 px-4 py-2 text-right sm:mr-0 sm:text-left sm:mt-0 sm:flex-row sm:gap-4 sm:flex sm:static">
    <li><%= link_to "Home", root_path, class: "text-xl sm:text-lg text-slate-200 hover:text-slate-400 font-medium" %></li>
    <% if user_signed_in? %>
      <li><%= link_to "Categories", categories_path, class: "text-xl sm:text-lg text-slate-200 hover:text-slate-400 font-medium" %></li>
      <li><%= link_to "Settings", edit_user_registration_path, class: "text-xl sm:text-lg text-slate-200 hover:text-slate-400 font-medium" %></li>
      <li><%= link_to "Log out", destroy_user_session_path, class: "text-xl sm:text-lg text-slate-200 hover:text-slate-400 font-medium" %></li>
    <% else %>
      <li><%= link_to "Log in", new_user_session_path, class: "text-xl sm:text-lg text-slate-200 hover:text-slate-400 font-medium" %></li>
      <li><%= link_to "Sign up", new_user_registration_path, class: "text-xl sm:text-lg text-slate-200 hover:text-slate-400 font-medium" %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"%>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= vite_client_tag %>
    <%= vite_typescript_tag 'application',  'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="bg-slate-200 min-h-[calc(100%-64px)] p-4 ">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_msg.html.erb
<% if object.errors.any? %>
  <div class="bg-slate-300 flex w-fit rounded border-2 border-red-400 m-auto mt-4 mb-6" id="error_explanation">
    <div class="w-20 bg-red-400 text-xl flex justify-center items-center p-6">
      <div class="border-2 rounded-full p-4 h-12 w-12 flex justify-center items-center border-slate-300 text-slate-300">X</div>
    </div>
    <div class="p-4">
      <p class="font-medium text-lg">There <%= format_auxiliary_verb(object.errors.count) %> <%= pluralize(object.errors.count, "error").upcase%> in your submission. </p>
      <ul class="list-disc list-inside">
        <% object.errors.full_messages.each do |message| %>
          <li> <%= message %>. </li>
        <%end%>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:success] || flash[:notice] %>
  <div class="bg-slate-300 flex w-fit rounded border-2 border-green-400 m-aut m-auto mt-4 mb-6" id="alert-success">
    <div class="w-20 bg-green-400 text-xl flex justify-center items-center p-6">
      <div class="border-2 rounded-full p-4 h-12 w-12 flex justify-center items-center border-white text-white">&#10003;</div>
    </div>
    <div class="p-4 flex flex-col justify-center">
      <p class="font-medium text-xl">SUCCESS</p>
      <p class="text-lg" id="alert-message"><%= flash[:success] || flash[:notice] %></p>
    </div>
  </div>
<% end %>
<% if flash[:danger] || flash[:alert] %>
  <div class="bg-slate-300 flex w-fit rounded border-2 border-red-400 m-auto mt-4 mb-6" id="alert-danger">
    <div class="w-20 bg-red-400 text-xl flex justify-center items-center p-6">
      <div class="border-2 rounded-full p-4 h-12 w-12 flex justify-center items-center border-slate-300 text-slate-300">X</div>
    </div>
    <div class="p-4 flex flex-col justify-center">
      <p class="font-medium text-xl">ERROR</p>
      <p class="text-lg" id="alert-message"><%= flash[:danger] || flash[:alert] %></p>
    </div>
  </div>
<% end %>

app/views/shared/_task_list.html.erb
<div class="lg:w-[calc(100%-128px)] m-auto" id="task-list">
  <h2 class="font-bold text-3xl mb-1">Today (<%= Date.current %>) - <%= @tasks_today.count %></h2>
  <div class='bg-slate-100 p-3 max-h-64 rounded overflow-y-auto'>
    <% if @tasks_today.count > 0 %>
      <ul class="flex flex-col gap-2">
        <%  @tasks_today.each do |task|%>
          <li class='flex justify-between items-center w-full bg-slate-300 rounded p-2 m-auto hover:bg-slate-400' >
            <%= form_with model: task, url: task_complete_path(task), method: task.completed? ? :delete : :post do |f| %>
              <%= f.check_box :completed, onchange: "this.form.submit()"; %>
            <% end %>
            <%= link_to task, class: 'w-full' do %>
              <div class="text-center">
                <p class="text-lg font-semibold"><%= task.name %></p>
                <p class="text-lg font-medium"><%= task.category.name %> • <span data-deadline><i class="las la-calendar-alt mr-1"></i><%= rephrase_deadline(task.deadline) %></span></p>
              </div>
            <% end %>
            <%= link_to task, method: :delete, data: { confirm: "Are you sure you want to delete this task?" } do %>
              <i class="las la-trash-alt cursor-pointer la-lg"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-center font-semibold text-xl">No Tasks today</p>
    <% end %>
  </div>
  <h2 class="font-bold text-3xl mt-2 mb-1">Tomorrow onwards - <%= @tasks_not_completed.count %></h2>
  <div class='bg-slate-100 p-3 max-h-64 rounded overflow-y-auto'>
    <% if @tasks_not_completed.count > 0 %>
      <ul class="flex flex-col gap-2">
        <% @tasks_not_completed.each do |task|%>
          <li class='flex justify-between items-center w-full <%= turn_to_red(task.deadline, task.completed) %> rounded p-2 m-auto hover:bg-slate-400'>
            <%= form_with model: task, url: task_complete_path(task), method: task.completed? ? :delete : :post do |f| %>
              <%= f.check_box :completed, onchange: "this.form.submit()"; %>
            <% end %>
            <%= link_to task, class: 'w-full' do %>
              <div class="text-center">
                <p class="text-lg font-semibold"><%= task.name %></p>
                <p class="text-lg font-medium"><%= task.category.name %> • <span data-deadline><i class="las la-calendar-alt mr-1"></i><%= rephrase_deadline(task.deadline) %></span></p>
              </div>
            <% end %>
            <%= link_to task, method: :delete, data: { confirm: "Are you sure you want to delete this task?" } do %>
              <i class="las la-trash-alt cursor-pointer la-lg"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-center font-semibold text-xl">No Tasks available</p>
    <% end %>
  </div>
  <div class="flex justify-between flex-wrap items-center mt-2 mb-1">
    <h2 class="font-bold text-3xl">Completed - <%= @tasks_completed.count %></h2>
    <% if @tasks_completed.count > 0%>
      <%= link_to conditional_destroy_completed_path(@category), method: :delete, data: { confirm: "Are you sure you want to delete all completed tasks#{' in this category' if @category}?" },
                                                                               class: 'bg-slate-400 px-2 py-1 rounded-md cursor-pointer font-medium text-md hover:bg-slate-500' do %>
        <i class="las la-trash-alt"></i>Delete Completed Tasks 
      <% end %>
    <% end %>
  </div>
  <div class='bg-slate-100 p-3 max-h-64 rounded overflow-y-auto'>
    <% if @tasks_completed.count > 0 %>
      <ul class="flex flex-col gap-2">
        <% @tasks_completed.each do |task|%>
          <li class='flex justify-between items-center w-full bg-slate-300 rounded p-2 m-auto hover:bg-slate-400'>
            <%= form_with model: task, url: task_complete_path(task), method: task.completed? ? :delete : :post do |f| %>
              <%= f.check_box :completed, value: task.completed, onchange: "this.form.submit()"; %>
            <% end %>
            <%= link_to task, class: 'w-full' do %>
              <div class="text-center">
                <p class="text-lg font-semibold line-through"><%= task.name %></p>
                <p class="text-lg font-medium"><%= task.category.name %> • <span><i class="las la-calendar-alt mr-1"></i><%= rephrase_deadline(task.deadline) %></span></p>
              </div>
            <% end %>
            <%= link_to task, method: :delete, data: { confirm: "Are you sure you want to delete this task?" } do %>
              <i class="las la-trash-alt cursor-pointer la-lg"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-center font-semibold text-xl">No Completed Tasks</p>
    <% end %>
  </div>
</div>

app/views/shared/flash.html.erb
<% if flash[:success] %>
  <div class="bg-slate-700 flex w-fit rounded border-2 border-green-400 m-aut m-auto my-6" id="alert-success">
    <div class="w-20 bg-green-400 text-xl flex justify-center items-center p-6">
      <div class="border-2 rounded-full p-4 h-12 w-12 flex justify-center items-center border-white text-white">&#10003;</div>
    </div>
    <div class="p-4 flex flex-col justify-center text-slate-300">
      <p class="font-medium text-xl">SUCCESS</p>
      <p class="text-lg"> <%= flash[:success] %></p>
    </div>
  </div>
<% end %>
<% if flash[:danger] %>
  <div class="bg-slate-700 flex w-fit rounded border-2 border-red-400 m-auto mt-6" id="alert-success">
    <div class="w-20 bg-red-400 text-xl flex justify-center items-center p-6">
      <div class="border-2 rounded-full p-4 h-12 w-12 flex justify-center items-center border-slate-300 text-slate-300">X</div>
    </div>
    <div class="p-4 flex flex-col justify-center text-slate-300">
      <p class="font-medium text-xl">ERROR</p>
      <p class="text-lg"> <%= flash[:danger] %></p>
    </div>
  </div>
<% end %>